#!/bin/sh

set -e

bundle exec jekyll build
bundle exec htmlproofer ./_site --check-html --alt-ignore '/.*/' --http-status-ignore "403,999" --url-ignore '/fonts.gstatic.com/'
bundle exec script/validate-html
gem build jekyll-theme-cayman.gemspec
